/**
 * Regenerates netlify.toml and vercel.json from csp.config.js.
 * Run with `npm run headers` after changing the policy, so the HTTP headers and the
 * meta tag baked into the bundle can never disagree.
 */
import { writeFileSync } from "node:fs";
import { buildCsp, SECURITY_HEADERS } from "../csp.config.js";

// Headers are static files, so they carry the default (no-proxy) policy. If you deploy
// an Anthropic proxy, add its origin to connect-src in both files by hand, or re-run
// this script with VITE_CLAUDE_PROXY_URL set.
const csp = buildCsp(process.env.VITE_CLAUDE_PROXY_URL || "");
const headers = SECURITY_HEADERS(csp);

const banner = `# GENERATED by scripts/gen-headers.mjs — edit csp.config.js and run \`npm run headers\`.
#
# The CSP is also injected as a <meta> tag at build time by vite.config.js, so the policy
# travels with the bundle to any host. These headers are the stronger form: frame-ancestors
# is ONLY honoured as a real header, never from a meta tag.`;

writeFileSync("netlify.toml", `${banner}

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
${Object.entries(headers).map(([k, v]) => `    ${k} = "${v}"`).join("\n")}

# Hashed asset filenames are content-addressed and safe to cache forever.
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
`);

writeFileSync("vercel.json", JSON.stringify({
  $schema: "https://openapi.vercel.sh/vercel.json",
  buildCommand: "npm run build",
  outputDirectory: "dist",
  headers: [
    { source: "/(.*)", headers: Object.entries(headers).map(([key, value]) => ({ key, value })) },
    { source: "/assets/(.*)", headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }] },
  ],
}, null, 2) + "\n");

console.log("Wrote netlify.toml and vercel.json");
console.log("CSP:", csp);
